In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
df = pd.read_csv(r"C:\Users\sk062\OneDrive\デスクトップ\西新宿 自動運転アンケート2025.2.21~24.csv　108名バージョン\西新宿 自動運転アンケート2025.2.21~24.csv")
df_copy = df.copy()

In [35]:
df_copy.columns

Index(['タイムスタンプ', '問１-１　個人属性について教えてください。', '問１-１　個人属性について教えてください。.1',
       '問１-２　あなたの立場に最も当てはまるものに〇をつけてください 。', '問１-３　あなたが住んでいる地域について〇をつけてください 。',
       '問１-４　過去に京王電鉄バスで行った自動運転バスの走行に乗車したことはありますか。',
       '問２-１　本日の自動運転車両を再度利用したいと思いますか？', '問２-２　再度の利用を希望する場合：理由を教えてください。（複数回答可）',
       '問２-２　再度の利用を希望しない場合：理由を教えてください。（複数回答可）',
       '問２-３　再度の利用を希望する場合：想定利用頻度を教えてください。',
       '問３-１　１回の利用について、運賃はいくらまでであれば支払うことが出来ますか？',
       '問４-１　普通の車両と比較して、乗車中に危険を感じる場面はありましたか？',
       '問４-２　危険を感じた場面：その場面を教えてください。（複数回答可）', '問5-１　今回の自動運転運行に参加した理由を教えてください。',
       '問5-２   今回の自動運転運行を何で知りましたか？',
       '問5-３　自動運転車両に乗った乗り心地の感想について、最もあてはまるものを選んでください',
       '問5-３　（上で選んだ）自動運転車両に乗った乗り心地の感想について、理由を教えてください',
       '問5-4　将来、地域公共交通として自動運転サービスがご自身の地域で実装される場合、期待することはなんですか？',
       '問5-4　（上で選んだ）将来、地域公共交通として自動運転サービスがご自身の地域で実装される場合、期待することについての、理由を教えてください',
       '問6-１-a　あなたは受益者（自動運転バス利用者）です。センサー（車両を検知するシステム）の誤作動防止のため、（あなたが車や自転車などの車両を運転している場合に）路上駐車や自転車での追い抜きを控える。',
       '問6-１-b　あなたは非受益者（自動運転バスを利用しない）です。センサー（車両

In [36]:
df_copy.columns = [
    "timestamp", "Q1-1_attribute_Sex", "Q1-1_attribute_Age", "Q1-2_position", "Q1-3_region",
    "Q1-4_past_autonomous_bus", "Q2-1_reuse_intent", "Q2-2_reason_reuse", "Q2-2_reason_no_reuse",
    "Q2-3_usage_frequency", "Q3-1_fare_willingness", "Q4-1_safety_concern", "Q4-2_safety_situation",
    "Q5-1_participation_reason", "Q5-2_info_source", "Q5-3_riding_comfort", "Q5-3_comfort_reason",
    "Q5-4_expectation_future", "Q5-4_expectation_reason",
    "Q6-1-a_beneficiary_parking", "Q6-1-b_non_beneficiary_parking",
    "Q6-2-a_beneficiary_pedestrian", "Q6-2-b_non_beneficiary_pedestrian",
    "Q6-3-a_beneficiary_speed_adjust", "Q6-3-b_non_beneficiary_speed_adjust",
    "Q6-4-a_beneficiary_financial_burden", "Q6-4-b_non_beneficiary_financial_burden",
    "Q7-1_self_service_acceptance"
]

df_copy.head()

timestamp Q1-1_attribute_Sex Q1-1_attribute_Age  \
0  2025/02/21 12:49:00 午後 GMT+9                 男性                40代   
1   2025/02/21 1:39:50 午後 GMT+9                 男性                30代   
2   2025/02/21 1:43:16 午後 GMT+9                 男性                50代   
3   2025/02/21 1:45:08 午後 GMT+9                 男性                40代   
4   2025/02/21 1:54:50 午後 GMT+9                 男性                40代   

  Q1-2_position Q1-3_region Q1-4_past_autonomous_bus Q2-1_reuse_intent  \
0           関係者        神奈川県                  初めて参加した            ④希望しない   
1           関係者         その他                  初めて参加した            ④希望しない   
2           関係者  東京都（23区以外）                  初めて参加した             ①希望する   
3           関係者  23区（新宿区以外）                  初めて参加した     ②どちらかというと希望する   
4           関係者  23区（新宿区以外）                  初めて参加した    ③どちらかというと希望しない   

  Q2-2_reason_reuse Q2-2_reason_no_reuse Q2-3_usage_frequency  ...  \
0               NaN          大半が手動運転だった。                  NaN  ...   
1               NaN   実証化には時間がかかるように感じた。                  NaN  ...   
2       ③希望する停留所がある                  NaN               ①週５回以上  ...   
3    ④他の交通手段より便利/早い                  NaN              ⑤年に数回以下  ...   
4               NaN      ⑤他の交通手段の方が便利/早い                  NaN  ...   

  Q5-4_expectation_reason Q6-1-a_beneficiary_parking  \
0                     NaN                   ②やや協力できる   
1               運転士不足への補完                        ③普通   
2                     NaN                 ①全面的に協力できる   
3                     NaN                        ③普通   
4                     NaN                        ③普通   

  Q6-1-b_non_beneficiary_parking Q6-2-a_beneficiary_pedestrian  \
0                       ②やや協力できる                     ④やや協力できない   
1                      ④やや協力できない                           ③普通   
2                     ①全面的に協力できる                    ①全面的に協力できる   
3                            ③普通                           ③普通   
4                      ④やや協力できない                      ②やや協力できる   

  Q6-2-b_non_beneficiary_pedestrian Q6-3-a_beneficiary_speed_adjust  \
0                         ④やや協力できない                       ④やや協力できない   
1                       ⑤全面的に協力できない                             ③普通   
2                        ①全面的に協力できる                      ①全面的に協力できる   
3                               ③普通                             ③普通   
4                         ④やや協力できない                        ②やや協力できる   

  Q6-3-b_non_beneficiary_speed_adjust Q6-4-a_beneficiary_financial_burden  \
0                           ④やや協力できない                                 ③普通   
1                         ⑤全面的に協力できない                         ⑤全面的に協力できない   
2                          ①全面的に協力できる                            ②やや協力できる   
3                                 ③普通                                 ③普通   
4                           ④やや協力できない                            ②やや協力できる   

  Q6-4-b_non_beneficiary_financial_burden  \
0                                     ③普通   
1                             ⑤全面的に協力できない   
2                                     ③普通   
3                                     ③普通   
4                               ④やや協力できない   

                        Q7-1_self_service_acceptance  
0  ②緊急時の通報;③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑤扉の開閉;...  
1      ②緊急時の通報;③車内の温度調節や窓の開閉;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス  
2            ②緊急時の通報;③車内の温度調節や窓の開閉;⑥チャージ含めた完全キャッシュレス  
3                                  ④行先や経路の確認（質問できない）  
4  ③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス  

[5 rows x 28 columns]

In [48]:
# for column in df_copy.columns:
#    print(f"列 '{column}' のユニークな値:")
#    print(df_copy[column].unique())
#    print()

In [44]:
print(df_copy.iloc[:, 1].unique())
print(df_copy.iloc[:, 2].unique())
print(df_copy.iloc[:, 3].unique())
print(df_copy.iloc[:, 4].unique())
print(df_copy.iloc[:, 5].unique())
print(df_copy.iloc[:, 6].unique())
print(df_copy.iloc[:, 7].unique())
print(df_copy.iloc[:, 8].unique())
print(df_copy.iloc[:, 9].unique())
print(df_copy.iloc[:, 10].unique())
print(df_copy.iloc[:, 11].unique())

['男性' '女性' '無回答']
['40代' '30代' '50代' '20代' '60代' '10代' '10代未満' '70代以上']
['関係者' '他地域からの来訪者' '地域住民']
['神奈川県' 'その他' '東京都（23区以外）' '23区（新宿区以外）' '新宿区']
['初めて参加した' '1回参加した' '複数回参加した' '今回試乗していない']
[4.0 1.0 2.0 3.0 nan]
[nan '③希望する停留所がある' '④他の交通手段より便利/早い' '①安全性を感じる' '②乗り方が簡単(予約等)'
 '②乗り方が簡単(予約等);③希望する停留所がある;④他の交通手段より便利/早い' '技術の進展を見届けたいから'
 '①安全性を感じる;②乗り方が簡単(予約等)' 'レベルが上がったらまた試乗してみたい' '乗っていてワクワクする'
 'どの程度、進化されたかを感じてみたいです' '精度が高まって実用化に近づくのを実感したい' 'おもしろい。'
 '②乗り方が簡単(予約等);③希望する停留所がある;⑤運行時間帯が適切' '今後の自動運転技術の向上を期待しているから。' '⑤運行時間帯が適切'
 '自動運転が興味深い' '昨年も乗らせていただいたが徐々に良くなっていると感じている。先が楽しみ'
 '自動運転技術進歩のため利用することで需要があることを示したいです' '③希望する停留所がある;④他の交通手段より便利/早い;⑤運行時間帯が適切'
 '①安全性を感じる;④他の交通手段より便利/早い' '予約無し希望' '自動運転バスの再乗車による評価'
 '①安全性を感じる;③希望する停留所がある' '技術の進歩を感じて面白い'
 'システムの解説が面白かったが、後部座席であったためモニターの表示を詳細に確認できなかった'
 '①安全性を感じる;運転士不足が今後影響が大きくなるので必要性を強く感じている' '③希望する停留所がある;新しいシステムに興味がある'
 '①安全性を感じる;③希望する停留所がある;まだ、自動運転が一般的ではないので興味本位'
 '①安全性を感じる;②乗り方が簡単(予約等);③希望する停留所がある;④他の交通手段より便利/早い' '①安全性を感じる;⑤運行時間帯が適切'
 '①安全性を感じる;自動運転をまた体験

In [45]:
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('①希望する', 1)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('②どちらかというと希望する', 2)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('③どちらかというと希望しない', 3)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('④希望しない', 4)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace("nan", 0)
df_copy.iloc[:, 6].unique()

array([4.0, 1.0, 2.0, 3.0, nan], dtype=object)

In [42]:
df_copy.iloc[:, 9].unique()

array([nan, '①週５回以上', '⑤年に数回以下', '④月に１～３回', '③週１～２回', '②週３～４回'],
      dtype=object)

In [46]:
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('①週５回以上', 1)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('②週３～４回', 2)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('③週１～２回', 3)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('④希望しない', 4)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('⑤年に数回以下', 5)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace("nan", 0)
df_copy.iloc[:, 9].unique()

array([nan, 1, 5, '④月に１～３回', 3, 2], dtype=object)

In [47]:
## ここから選択肢がある場合は数字の選択式にする