In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
df = pd.read_csv(r"C:\Users\sk062\OneDrive\デスクトップ\西新宿 自動運転アンケート2025.2.21~24.csv　108名バージョン\西新宿 自動運転アンケート2025.2.21~24.csv")
df_copy = df.copy()

In [87]:
# df_copy.columns

In [88]:
df_copy.columns = [
    "timestamp", "Q1-1_attribute_Sex", "Q1-1_attribute_Age", "Q1-2_position", "Q1-3_region",
    "Q1-4_past_autonomous_bus", "Q2-1_reuse_intent", "Q2-2_reason_reuse", "Q2-2_reason_no_reuse",
    "Q2-3_usage_frequency", "Q3-1_fare_willingness", "Q4-1_safety_concern", "Q4-2_safety_situation",
    "Q5-1_participation_reason", "Q5-2_info_source", "Q5-3_riding_comfort", "Q5-3_comfort_reason",
    "Q5-4_expectation_future", "Q5-4_expectation_reason",
    "Q6-1-a_beneficiary_parking", "Q6-1-b_non_beneficiary_parking",
    "Q6-2-a_beneficiary_pedestrian", "Q6-2-b_non_beneficiary_pedestrian",
    "Q6-3-a_beneficiary_speed_adjust", "Q6-3-b_non_beneficiary_speed_adjust",
    "Q6-4-a_beneficiary_financial_burden", "Q6-4-b_non_beneficiary_financial_burden",
    "Q7-1_self_service_acceptance"
]

# df_copy.head()

In [89]:
# for column in df_copy.columns:
#    print(f"列 '{column}' のユニークな値:")
#    print(df_copy[column].unique())
#    print()

In [90]:
#print(df_copy.iloc[:, 1].unique())
#print(df_copy.iloc[:, 2].unique())
#print(df_copy.iloc[:, 3].unique())
#print(df_copy.iloc[:, 4].unique())
#print(df_copy.iloc[:, 5].unique())
#print(df_copy.iloc[:, 6].unique())
#print(df_copy.iloc[:, 7].unique())
#print(df_copy.iloc[:, 8].unique())
#print(df_copy.iloc[:, 9].unique())
#print(df_copy.iloc[:, 10].unique())
#print(df_copy.iloc[:, 11].unique())

In [91]:
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('①希望する', 1)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('②どちらかというと希望する', 2)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('③どちらかというと希望しない', 3)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('④希望しない', 4)
df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace("nan", 0)
df_copy.iloc[:, 6].unique()

C:\Users\sk062\AppData\Local\Temp\ipykernel_7332\1514456383.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy.iloc[:, 6] = df_copy.iloc[:, 6].replace('④希望しない', 4)


array([4.0, 1.0, 2.0, 3.0, nan], dtype=object)

In [92]:
df_copy.iloc[:, 9].unique()

array([nan, '①週５回以上', '⑤年に数回以下', '④月に１～３回', '③週１～２回', '②週３～４回'],
      dtype=object)

In [93]:
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('①週５回以上', 1)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('②週３～４回', 2)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('③週１～２回', 3)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('④希望しない', 4)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace('⑤年に数回以下', 5)
df_copy.iloc[:, 9] = df_copy.iloc[:, 9].replace("nan", 0)
df_copy.iloc[:, 9].unique()

array([nan, 1, 5, '④月に１～３回', 3, 2], dtype=object)

In [94]:
## ここから選択肢がある場合は数字の選択式にする

In [95]:
df_copy.iloc[:, 10].unique()

array(['②１５０円', '①１００円以下', '③２００円', nan, '④２５０円', '⑤３００円'], dtype=object)

In [96]:
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('①１００円以下', 1)
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('②１５０円', 2)
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('③２００円', 3)
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('④２５０円', 4)
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('⑤３００円', 5)
df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace("nan", 0)
df_copy.iloc[:, 10].unique()

C:\Users\sk062\AppData\Local\Temp\ipykernel_7332\1016292228.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy.iloc[:, 10] = df_copy.iloc[:, 10].replace('⑤３００円', 5)


array([2.0, 1.0, 3.0, nan, 4.0, 5.0], dtype=object)

In [97]:
df_copy.iloc[:, 11].unique()

array(['②危険を感じなかった', '①危険を感じた', nan], dtype=object)

In [98]:
df_copy.iloc[:, 11] = df_copy.iloc[:, 11].replace('①危険を感じた', 1)
df_copy.iloc[:, 11] = df_copy.iloc[:, 11].replace('②危険を感じなかった', 2)
df_copy.iloc[:, 11] = df_copy.iloc[:, 11].replace("nan", 0)
df_copy.iloc[:, 11].unique()

C:\Users\sk062\AppData\Local\Temp\ipykernel_7332\3817273922.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy.iloc[:, 11] = df_copy.iloc[:, 11].replace('②危険を感じなかった', 2)


array([2.0, 1.0, nan], dtype=object)

In [99]:
list(df_copy.iloc[:, 13].unique())

['③試しに乗ってみた（視察含む）',
 '⑪行政機関利用',
 '⑤自動運動システムに興味があった',
 '⑧業務',
 '①興味本位',
 '⑨趣味・コミュニティ活動',
 nan,
 '②家族・友人に誘われたから']

In [103]:
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('①興味本位', 1)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('②家族・友人に誘われたから', 2)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('③試しに乗ってみた（視察含む）', 3)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑤自動運動システムに興味があった', 5)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑥通勤（都庁）', 6)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑦通勤（都庁以外）', 7)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑧業務', 8)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑨趣味・コミュニティ活動', 9)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑩通院/健康関係', 10)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑪行政機関利用', 11)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑫金融/郵便関係利用', 12)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑬外食', 13)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑭日用品の購入', 14)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑮（日用品を除く）物品の購入/サービス契約', 15)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('⑯仕事以外の方（知人/友人/家族等）の面会', 16)
df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace("nan", 0)
df_copy.iloc[:, 13].unique()

C:\Users\sk062\AppData\Local\Temp\ipykernel_7332\2695788101.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy.iloc[:, 13] = df_copy.iloc[:, 13].replace('③試しに乗ってみた（視察含む）', 3)


array([3.0, 11.0, 5.0, 8.0, 1.0, 9.0, nan, 2.0], dtype=object)

In [105]:
df_copy.iloc[:, 19].unique()

array(['②やや協力できる', '③普通', '①全面的に協力できる', '⑤全面的に協力できない', '④やや協力できない'],
      dtype=object)

In [122]:
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace('②やや協力できる', 2)
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace('③普通', 3)
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace('④やや協力できない', 4)
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 19] = df_copy.iloc[:, 19].replace("nan", 0)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace('②やや協力できる', 2)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace('③普通', 3)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace('④やや協力できない', 4)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 20] = df_copy.iloc[:, 20].replace("nan", 0)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace('②やや協力できる', 2)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace('③普通', 3)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace('④やや協力できない', 4)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 21] = df_copy.iloc[:, 21].replace("nan", 0)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace('②やや協力できる', 2)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace('③普通', 3)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace('④やや協力できない', 4)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 22] = df_copy.iloc[:, 22].replace("nan", 0)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace('②やや協力できる', 2)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace('③普通', 3)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace('④やや協力できない', 4)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 23] = df_copy.iloc[:, 23].replace("nan", 0)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace('②やや協力できる', 2)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace('③普通', 3)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace('④やや協力できない', 4)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 24] = df_copy.iloc[:, 24].replace("nan", 0)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace('②やや協力できる', 2)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace('③普通', 3)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace('④やや協力できない', 4)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 25] = df_copy.iloc[:, 25].replace("nan", 0)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('①全面的に協力できる', 1)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('②やや協力できる', 2)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('③普通', 3)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('④やや協力できない', 4)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('⑤全面的に協力できない', 5)
df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace("nan", 0)
print(df_copy.iloc[:, 19].unique())
print(df_copy.iloc[:, 20].unique())
print(df_copy.iloc[:, 21].unique())
print(df_copy.iloc[:, 22].unique())
print(df_copy.iloc[:, 23].unique())
print(df_copy.iloc[:, 24].unique())
print(df_copy.iloc[:, 25].unique())
print(df_copy.iloc[:, 26].unique())

[4.0 1.0 2.0 3.0 nan]
[2 4 1 3 5]
[4 3 1 2 5]
[4 5 1 3 2]
[4 3 1 2 5]
[4 5 1 3 2]
[3 5 2 4 1]
[3 5 4 2 1]


C:\Users\sk062\AppData\Local\Temp\ipykernel_7332\3722213738.py:47: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_copy.iloc[:, 26] = df_copy.iloc[:, 26].replace('⑤全面的に協力できない', 5)


In [123]:
df_copy.iloc[:, 27].unique()

array(['②緊急時の通報;③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '②緊急時の通報;③車内の温度調節や窓の開閉;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '②緊急時の通報;③車内の温度調節や窓の開閉;⑥チャージ含めた完全キャッシュレス', '④行先や経路の確認（質問できない）',
       '③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス',
       '④行先や経路の確認（質問できない）;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '①乗車にサポートが必要な方へ他の乗客によるサポート;②緊急時の通報;⑤扉の開閉',
       '②緊急時の通報;⑥チャージ含めた完全キャッシュレス',
       '①乗車にサポートが必要な方へ他の乗客によるサポート;②緊急時の通報;③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '①乗車にサポートが必要な方へ他の乗客によるサポート;②緊急時の通報;④行先や経路の確認（質問できない）;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '②緊急時の通報;④行先や経路の確認（質問できない）;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '②緊急時の通報;④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス',
       '②緊急時の通報;③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス',
       '④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス', '②緊急時の通報',
       '①乗車にサポートが必要な方へ他の乗客によるサポート;②緊急時の通報;⑤扉の開閉;⑥チャージ含めた完全キャッシュレス',
       '①乗車にサポートが必要な方へ他の乗客によるサポート;②緊急時の通報;④行先や経路の確認（質問できない）;⑥チャージ含めた完全キャッシュレス',
       '①乗車にサポートが必要な方へ他の乗客によ

In [135]:
pd.set_option('display.max_columns', 40)

In [136]:
df_copy = df_copy.fillna(0)
df_copy.head(1)

timestamp Q1-1_attribute_Sex Q1-1_attribute_Age  \
0  2025/02/21 12:49:00 午後 GMT+9                 男性                40代   

  Q1-2_position Q1-3_region Q1-4_past_autonomous_bus  Q2-1_reuse_intent  \
0           関係者        神奈川県                  初めて参加した                4.0   

  Q2-2_reason_reuse Q2-2_reason_no_reuse Q2-3_usage_frequency  \
0                 0          大半が手動運転だった。                    0   

   Q3-1_fare_willingness  Q4-1_safety_concern Q4-2_safety_situation  \
0                    2.0                  2.0                     0   

   Q5-1_participation_reason Q5-2_info_source Q5-3_riding_comfort  \
0                        3.0        ⑧関係者から聞いて               ④やや不満   

   Q5-3_comfort_reason Q5-4_expectation_future Q5-4_expectation_reason  \
0  自動と手動の切替時にカクカクしていた。           ①運行便数（ダイヤ）の増加                       0   

   Q6-1-a_beneficiary_parking  Q6-1-b_non_beneficiary_parking  \
0                         4.0                               2   

   Q6-2-a_beneficiary_pedestrian  Q6-2-b_non_beneficiary_pedestrian  \
0                              4                                  4   

   Q6-3-a_beneficiary_speed_adjust  Q6-3-b_non_beneficiary_speed_adjust  \
0                                4                                    4   

   Q6-4-a_beneficiary_financial_burden  \
0                                    3   

   Q6-4-b_non_beneficiary_financial_burden  \
0                                        3   

                        Q7-1_self_service_acceptance  
0  ②緊急時の通報;③車内の温度調節や窓の開閉;④行先や経路の確認（質問できない）;⑤扉の開閉;...

In [127]:
df_copy.dtypes

timestamp                                   object
Q1-1_attribute_Sex                          object
Q1-1_attribute_Age                          object
Q1-2_position                               object
Q1-3_region                                 object
Q1-4_past_autonomous_bus                    object
Q2-1_reuse_intent                          float64
Q2-2_reason_reuse                           object
Q2-2_reason_no_reuse                        object
Q2-3_usage_frequency                        object
Q3-1_fare_willingness                      float64
Q4-1_safety_concern                        float64
Q4-2_safety_situation                       object
Q5-1_participation_reason                  float64
Q5-2_info_source                            object
Q5-3_riding_comfort                         object
Q5-3_comfort_reason                         object
Q5-4_expectation_future                     object
Q5-4_expectation_reason                     object
Q6-1-a_beneficiary_parking     

In [152]:
df_copy.iloc[:, 5].unique()

array(['初めて参加した', '1回参加した', '複数回参加した', '今回試乗していない'], dtype=object)

In [157]:
# '今回試乗していない' の行のみを含むデータフレーム
df_not_tested = df_copy[df_copy.iloc[:, 5] == '今回試乗していない']

# '今回試乗していない' の行を除外したデータフレーム
df_tested = df_copy[df_copy.iloc[:, 5] != '今回試乗していない']

print(len(df_not_tested))
print(len(df_tested))

27
81


In [148]:
print(df_copy.iloc[:, 6].unique())

[4. 1. 2. 3. 0.]


In [146]:
print(df_copy.iloc[:, 4])
print("-------------------")
print(df_copy.iloc[:, 6])

0            神奈川県
1             その他
2      東京都（23区以外）
3      23区（新宿区以外）
4      23区（新宿区以外）
          ...    
103    23区（新宿区以外）
104    東京都（23区以外）
105           その他
106          神奈川県
107    23区（新宿区以外）
Name: Q1-3_region, Length: 108, dtype: object
-------------------
0      4.0
1      4.0
2      1.0
3      2.0
4      3.0
      ... 
103    2.0
104    1.0
105    2.0
106    0.0
107    3.0
Name: Q2-1_reuse_intent, Length: 108, dtype: float64


In [143]:
print(df_copy.groupby([df_copy.iloc[:, 4], df_copy.iloc[:, 6]]).size())

Q1-3_region  Q2-1_reuse_intent
23区（新宿区以外）   0.0                   8
             1.0                  13
             2.0                  11
             3.0                   5
その他          0.0                   3
             1.0                   5
             2.0                   9
             3.0                   2
             4.0                   1
新宿区          0.0                   1
             1.0                   1
             3.0                   2
東京都（23区以外）   0.0                   5
             1.0                   9
             2.0                   8
             3.0                   3
神奈川県         0.0                  10
             1.0                   3
             2.0                   5
             3.0                   3
             4.0                   1
dtype: int64


In [160]:
# 絶対パスまたは相対パスを指定して保存
df_copy.to_csv(r"C:\Users\sk062\OneDrive\デスクトップ\変換後データ1.csv", index=False)  # インデックスなし
df_not_tested.to_csv(r"C:\Users\sk062\OneDrive\デスクトップ\変換後データ1.csv", index=False)  # インデックスなし